# Generated by Django 5.0.1 on 2024-01-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Título', max_length=200),
            preserve_default=False,
        ),
    ]
