# Generated by Django 5.0.1 on 2024-01-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='titulo', max_length=200),
            preserve_default=False,
        ),
    ]
