# Generated by Django 5.0.1 on 2024-01-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_post_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
    ]
