# Generated by Django 5.0.1 on 2024-01-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(default='descripcion descripcion descripcion', max_length=600),
            preserve_default=False,
        ),
    ]
