# Generated by Django 5.0.1 on 2024-01-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_post_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='fichaTecnicaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='infoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('birthday', models.DateField()),
                ('prefijo_telefono', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
