# Generated by Django 5.0.1 on 2024-01-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_fichatecnicausuario_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnicausuario',
            name='phone_number',
            field=models.CharField(default='no number', max_length=12),
            preserve_default=False,
        ),
    ]
